//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

using AmphibianSoftware.VisualSail.PostBuild;
// 
// This source code was auto-generated by wsdl, Version=2.0.50727.1432.
// 
namespace AmphibianSoftware.VisualSail.WebServices
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ActivationServiceSoap", Namespace = "http://visualsail.com/")]
    [DoNotObfuscate()]
    public partial class ActivationService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {
        [DoNotObfuscate()]
        private System.Threading.SendOrPostCallback RequestActivationOperationCompleted;

        /// <remarks/>
        [DoNotObfuscate()]
        public ActivationService()
        {
            this.Url = "http://www.visualsail.com/Services/ActivationService.asmx";
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public event RequestActivationCompletedEventHandler RequestActivationCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://visualsail.com/RequestActivation", RequestNamespace = "http://visualsail.com/", ResponseNamespace = "http://visualsail.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [DoNotObfuscate()]
        public ActivationResponse RequestActivation(string hardwareID, string appKey, string googleOrderNumber, string serialNumber, string email, string firstName, string lastName, string boatClass, string homePort)
        {
            object[] results = this.Invoke("RequestActivation", new object[] {
                    hardwareID,
                    appKey,
                    googleOrderNumber,
                    serialNumber,
                    email,
                    firstName,
                    lastName,
                    boatClass,
                    homePort});
            return ((ActivationResponse)(results[0]));
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public System.IAsyncResult BeginRequestActivation(string hardwareID, string appKey, string googleOrderNumber, string serialNumber, string email, string firstName, string lastName, string boatClass, string homePort, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("RequestActivation", new object[] {
                    hardwareID,
                    appKey,
                    googleOrderNumber,
                    serialNumber,
                    email,
                    firstName,
                    lastName,
                    boatClass,
                    homePort}, callback, asyncState);
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public ActivationResponse EndRequestActivation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ActivationResponse)(results[0]));
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public void RequestActivationAsync(string hardwareID, string appKey, string googleOrderNumber, string serialNumber, string email, string firstName, string lastName, string boatClass, string homePort)
        {
            this.RequestActivationAsync(hardwareID, appKey, googleOrderNumber, serialNumber, email, firstName, lastName, boatClass, homePort, null);
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public void RequestActivationAsync(string hardwareID, string appKey, string googleOrderNumber, string serialNumber, string email, string firstName, string lastName, string boatClass, string homePort, object userState)
        {
            if ((this.RequestActivationOperationCompleted == null))
            {
                this.RequestActivationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestActivationOperationCompleted);
            }
            this.InvokeAsync("RequestActivation", new object[] {
                    hardwareID,
                    appKey,
                    googleOrderNumber,
                    serialNumber,
                    email,
                    firstName,
                    lastName,
                    boatClass,
                    homePort}, this.RequestActivationOperationCompleted, userState);
        }
        [DoNotObfuscate()]
        private void OnRequestActivationOperationCompleted(object arg)
        {
            if ((this.RequestActivationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestActivationCompleted(this, new RequestActivationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://visualsail.com/")]
    [DoNotObfuscate]
    public partial class ActivationResponse
    {
        [DoNotObfuscate()]
        private string messageField;
        [DoNotObfuscate()]
        private byte[] licenseField;

        /// <remarks/>
        [DoNotObfuscate()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        [DoNotObfuscate()]
        public byte[] License
        {
            get
            {
                return this.licenseField;
            }
            set
            {
                this.licenseField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [DoNotObfuscate()]
    public delegate void RequestActivationCompletedEventHandler(object sender, RequestActivationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.1432")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [DoNotObfuscate]
    public partial class RequestActivationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        [DoNotObfuscate()]
        private object[] results;
        [DoNotObfuscate()]
        internal RequestActivationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        [DoNotObfuscate()]
        public ActivationResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ActivationResponse)(this.results[0]));
            }
        }
    }
}